import type { ImageType, ExperienceType } from './types';

export const NAV_CATEGORIES = ['Todos', 'Triathlon', 'Corrida', 'Ginastica Ritmica', 'Futebol', 'Beach Tennis', 'Musculação'];

export const MAIN_NAV_LINKS = [
  { name: 'Portfólio', href: '#portfolio' },
  { name: 'Experiências', href: '#experiencias' },
  { name: 'Contato', href: '#contato' },
];

export const PORTFOLIO_IMAGES: ImageType[] = [
  {
    id: 10,
    src: "/images/beach-tennis/@WANDSEVEN - BT-1594.jpg",
    alt: "Beach tennis player smiling",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 11,
    src: "/images/beach-tennis/@WANDSEVEN - BT-1714.jpg",
    alt: "Beach tennis players discussing",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 12,
    src: "/images/beach-tennis/@WANDSEVEN - BT-1757.jpg",
    alt: "Beach tennis player serving",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 13,
    src: "/images/beach-tennis/@WANDSEVEN - BT-1799.jpg",
    alt: "Beach tennis player in action",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 14,
    src: "/images/beach-tennis/@WANDSEVEN - BT-1881.jpg",
    alt: "Beach tennis players high-fiving",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 15,
    src: "/images/beach-tennis/@WANDSEVEN - BT-2638.jpg",
    alt: "Beach tennis player hitting the ball",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 16,
    src: "/images/beach-tennis/@WANDSEVEN - BT-2907.jpg",
    alt: "Beach tennis player looking at the camera",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 17,
    src: "/images/beach-tennis/@WANDSEVEN - BT-2952.jpg",
    alt: "Beach tennis players celebrating",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 18,
    src: "/images/beach-tennis/@WANDSEVEN - BT-3000.jpg",
    alt: "Beach tennis players smiling",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 19,
    src: "/images/beach-tennis/@WANDSEVEN - BT-3425.jpg",
    alt: "Beach tennis player preparing to serve",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 20,
    src: "/images/beach-tennis/@WANDSEVEN - BT-4046.jpg",
    alt: "Beach tennis player hitting the ball",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 21,
    src: "/images/beach-tennis/@WANDSEVEN - BT-4127.jpg",
    alt: "Beach tennis player jumping to hit the ball",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 22,
    src: "/images/beach-tennis/INSTAGRAM @WANDSEVEN -74.jpg",
    alt: "Beach tennis player focused",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 23,
    src: "/images/beach-tennis/INSTAGRAM @WANDSEVEN -251.jpg",
    alt: "Beach tennis player smiling",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 24,
    src: "/images/beach-tennis/INSTAGRAM @WANDSEVEN -263.jpg",
    alt: "Beach tennis players shaking hands",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 25,
    src: "/images/beach-tennis/INSTAGRAM @WANDSEVEN -1822.jpg",
    alt: "Beach tennis player focused",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 26,
    src: "/images/beach-tennis/INSTAGRAM @WANDSEVEN -2165.jpg",
    alt: "Beach tennis player focused",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 27,
    src: "/images/beach-tennis/INSTAGRAM @WANDSEVEN -2678.jpg",
    alt: "Beach tennis player focused",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 28,
    src: "/images/beach-tennis/INSTAGRAM @WANDSEVEN -2797.jpg",
    alt: "Beach tennis player focused",
    location: "Quadra de Areia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Beach Tennis",
  },
  {
    id: 29,
    src: "/images/corrida/@WANDSEVEN -128.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 30,
    src: "/images/corrida/@WANDSEVEN -153.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 31,
    src: "/images/corrida/@WANDSEVEN -305.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 32,
    src: "/images/corrida/@WANDSEVEN -523.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 33,
    src: "/images/corrida/@WANDSEVEN -896.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 34,
    src: "/images/corrida/@WANDSEVEN -996.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 35,
    src: "/images/corrida/@WANDSEVEN -1014.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 36,
    src: "/images/corrida/@WANDSEVEN -3016.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 37,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN - NEW BALANCE-5883.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 38,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN - NEW BALANCE-6800.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 39,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN - NEW BALANCE-7212.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 40,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN - NEW BALANCE-7355.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 41,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN - NEW BALANCE-7405.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 42,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN - NEW BALANCE-7477.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 43,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN - NEW BALANCE-7886 (1).jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 44,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN - NEW BALANCE-7886.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 45,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN - NEW BALANCE-8000.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 46,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN - NEW BALANCE-8136.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 47,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-658.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 48,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-756.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 49,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-834.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 50,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-904.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 51,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-1120.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 52,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-2597.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 53,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-3038.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 54,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-3069.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 55,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-3463.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 56,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-3485.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 57,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-4447.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 58,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-5094.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 59,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-6327.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 60,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-14513.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 61,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-19125.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 62,
    src: "/images/corrida/INSTAGRAM @WANDSEVEN-20033.jpg",
    alt: "Corredores em uma corrida de rua",
    location: "Corrida de Rua",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Corrida",
  },
  {
    id: 63,
    src: "/images/futebol/@WANDSEVEN - TREINO N9-12.jpg",
    alt: "Jogador de futebol em treino",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 64,
    src: "/images/futebol/@WANDSEVEN - TREINO N9-69.jpg",
    alt: "Jogador de futebol em treino",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 65,
    src: "/images/futebol/@WANDSEVEN - TREINO N9-94.jpg",
    alt: "Jogador de futebol em treino",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 66,
    src: "/images/futebol/amistoso n9 vs l10 @wandseven-204.jpg",
    alt: "Amistoso de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 67,
    src: "/images/futebol/amistoso n9 vs l10 @wandseven-387.jpg",
    alt: "Amistoso de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 68,
    src: "/images/futebol/amistoso n9 vs l10 @wandseven-705.jpg",
    alt: "Amistoso de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 69,
    src: "/images/futebol/INSTAGRAM @WANDSEVEN -335.jpg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 70,
    src: "/images/futebol/INSTAGRAM @WANDSEVEN -5884.jpg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 71,
    src: "/images/futebol/INSTAGRAM @WANDSEVEN -5947.jpg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 72,
    src: "/images/futebol/INSTAGRAM @WANDSEVEN -6107.jpg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 73,
    src: "/images/futebol/INSTAGRAM @WANDSEVEN -6231.jpg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 74,
    src: "/images/futebol/WhatsApp Image 2025-09-14 at 17.42.01 (1).jpeg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 75,
    src: "/images/futebol/WhatsApp Image 2025-09-14 at 17.42.01.jpeg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 76,
    src: "/images/futebol/WhatsApp Image 2025-09-14 at 17.42.02 (3).jpeg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 77,
    src: "/images/futebol/WhatsApp Image 2025-09-14 at 17.42.02 (4).jpeg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 78,
    src: "/images/futebol/WhatsApp Image 2025-09-14 at 17.42.02.jpeg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 79,
    src: "/images/futebol/WhatsApp Image 2025-09-14 at 17.42.03.jpeg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 80,
    src: "/images/futebol/WhatsApp Image 2025-09-14 at 17.42.04.jpeg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 81,
    src: "/images/futebol/WhatsApp Image 2025-09-14 at 17.42.05.jpeg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 82,
    src: "/images/futebol/WhatsApp Image 2025-09-14 at 17.42.08.jpeg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 83,
    src: "/images/futebol/WhatsApp Image 2025-09-14 at 17.42.09.jpeg",
    alt: "Jogador de futebol",
    location: "Campo de Futebol",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "800", aperture: "f/2.8" },
    category: "Futebol",
  },
  {
    id: 84,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-496.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 85,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-2003.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 86,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-2198.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 87,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-2924.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 88,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-3452.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 89,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-3749.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 90,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-3828.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 91,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-6100.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 92,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-6538.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 93,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-11237.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 94,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-11986.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 95,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-12068.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 96,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-12178.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 97,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-12197.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 98,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-12801.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 99,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-12862.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 100,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-12977.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 101,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-12990.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 102,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-13000.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 103,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-13482.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 104,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-13553.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 105,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-13719.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 106,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-14195.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 107,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-14464.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 108,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-14794.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 109,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-14903.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 110,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-15238.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 111,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-15846.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 112,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-15888.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 113,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-20044.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 114,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-21555.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 115,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-21694.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 116,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-24047.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 117,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-30219.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 118,
    src: "/images/ginastica-ritmica/INSTAGRAM @WANDSEVEN-30333.jpg",
    alt: "Ginasta rítmica em apresentação",
    location: "Arena Santos",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1250s", iso: "2500", aperture: "f/2.8" },
    category: "Ginastica Ritmica",
  },
  {
    id: 119,
    src: "/images/musculacao/@wandseven - treino allfit 0809-39.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 120,
    src: "/images/musculacao/@wandseven - treino allfit 0809-181.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 121,
    src: "/images/musculacao/@wandseven - treino allfit 0809-243.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 122,
    src: "/images/musculacao/@wandseven - treino allfit 0809-317.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 123,
    src: "/images/musculacao/@wandseven - treino allfit 0809-368.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 124,
    src: "/images/musculacao/@wandseven - treino allfit 0809-512.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 125,
    src: "/images/musculacao/@wandseven - treino allfit 0809-715.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 126,
    src: "/images/musculacao/@wandseven - treino allfit 0809-819.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 127,
    src: "/images/musculacao/@wandseven - TREINO ALLFIT 1509-148.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 128,
    src: "/images/musculacao/@wandseven - TREINO ALLFIT 1509-783.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 129,
    src: "/images/musculacao/@wandseven - TREINO ALLFIT 1509-816.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 130,
    src: "/images/musculacao/all fit 1005 @wandseven-299.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 131,
    src: "/images/musculacao/all fit 1305 @wandseven-335.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 132,
    src: "/images/musculacao/INSTAGRAM @WANDSEVEN -39.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 133,
    src: "/images/musculacao/INSTAGRAM @WANDSEVEN -349.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 134,
    src: "/images/musculacao/INSTAGRAM @WANDSEVEN -381.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 135,
    src: "/images/musculacao/INSTAGRAM @WANDSEVEN -718.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 136,
    src: "/images/musculacao/INSTAGRAM @WANDSEVEN -734.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 137,
    src: "/images/musculacao/INSTAGRAM @WANDSEVEN -800.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  {
    id: 138,
    src: "/images/musculacao/treino allfit 2405 @wandseven-631.jpg",
    alt: "Pessoa treinando musculação",
    location: "Academia",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/250s", iso: "800", aperture: "f/2.8" },
    category: "Musculação",
  },
  // New Triathlon Images
  {
    id: 139,
    src: "/images/triathlon/@wandseven - BIKE-169.jpg",
    alt: "Ciclista em prova de triathlon",
    location: "Percurso de Ciclismo",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 140,
    src: "/images/triathlon/@wandseven - BIKE-182.jpg",
    alt: "Ciclista em prova de triathlon",
    location: "Percurso de Ciclismo",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 141,
    src: "/images/triathlon/@wandseven - BIKE-197.jpg",
    alt: "Ciclista em prova de triathlon",
    location: "Percurso de Ciclismo",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 142,
    src: "/images/triathlon/@wandseven - BIKE-222.jpg",
    alt: "Ciclista em prova de triathlon",
    location: "Percurso de Ciclismo",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 143,
    src: "/images/triathlon/@wandseven - BIKE-237.jpg",
    alt: "Ciclista em prova de triathlon",
    location: "Percurso de Ciclismo",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 144,
    src: "/images/triathlon/@wandseven - BIKE-1308.jpg",
    alt: "Ciclista em prova de triathlon",
    location: "Percurso de Ciclismo",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 145,
    src: "/images/triathlon/@wandseven - BIKE-1324.jpg",
    alt: "Ciclista em prova de triathlon",
    location: "Percurso de Ciclismo",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 146,
    src: "/images/triathlon/@wandseven - BIKE-1488.jpg",
    alt: "Ciclista em prova de triathlon",
    location: "Percurso de Ciclismo",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 147,
    src: "/images/triathlon/@wandseven - BIKE-1516.jpg",
    alt: "Ciclista em prova de triathlon",
    location: "Percurso de Ciclismo",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 148,
    src: "/images/triathlon/@wandseven - BIKE-2263.jpg",
    alt: "Ciclista em prova de triathlon",
    location: "Percurso de Ciclismo",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 149,
    src: "/images/triathlon/@wandseven - CORRIDA-453.jpg",
    alt: "Corredor em prova de triathlon",
    location: "Percurso de Corrida",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 150,
    src: "/images/triathlon/@wandseven - CORRIDA-685.jpg",
    alt: "Corredor em prova de triathlon",
    location: "Percurso de Corrida",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 151,
    src: "/images/triathlon/@wandseven - CORRIDA-704.jpg",
    alt: "Corredor em prova de triathlon",
    location: "Percurso de Corrida",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 152,
    src: "/images/triathlon/@wandseven - CORRIDA-878.jpg",
    alt: "Corredor em prova de triathlon",
    location: "Percurso de Corrida",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 153,
    src: "/images/triathlon/@wandseven - CORRIDA-917.jpg",
    alt: "Corredor em prova de triathlon",
    location: "Percurso de Corrida",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 154,
    src: "/images/triathlon/@wandseven - CORRIDA-1006.jpg",
    alt: "Corredor em prova de triathlon",
    location: "Percurso de Corrida",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 155,
    src: "/images/triathlon/@wandseven-263.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 156,
    src: "/images/triathlon/@wandseven-581.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 157,
    src: "/images/triathlon/@wandseven-600.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 158,
    src: "/images/triathlon/@wandseven-617.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 159,
    src: "/images/triathlon/@wandseven-627.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 160,
    src: "/images/triathlon/@wandseven-1079.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 161,
    src: "/images/triathlon/@wandseven-1232.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 162,
    src: "/images/triathlon/@wandseven-1285.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 163,
    src: "/images/triathlon/@wandseven-1340.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 164,
    src: "/images/triathlon/@wandseven-1424.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 165,
    src: "/images/triathlon/@wandseven-1592.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 166,
    src: "/images/triathlon/@wandseven-1677.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 167,
    src: "/images/triathlon/@wandseven-1897.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
  {
    id: 168,
    src: "/images/triathlon/@wandseven-1969.jpg",
    alt: "Atleta saindo da água no triathlon",
    location: "Natação",
    equipment: "Câmera Profissional",
    settings: { shutter: "1/1000s", iso: "400", aperture: "f/2.8" },
    category: "Triathlon",
  },
];

export const EXPERIENCES: ExperienceType[] = [
  {
    id: 1,
    company: "Desafios de Corrida",
    description: "Participei de 4 Brutus Race e 3 Bravus Race — desafios que testaram meus limites físicos e mentais, reforçando minha disciplina, resistência e espírito de equipe.",
    period: "2018 - Presente",
  },
  {
    id: 2,
    company: "Corridas de Rua Nacionais",
    description: "Fui selecionado para participar de 4 edições da tradicional Corrida Internacional de São Silvestre e de 4 edições dos 10 km da Tribuna, em Santos — eventos de grande relevância no cenário das corridas de rua no Brasil, que exigem preparo físico, foco e dedicação contínua.",
    period: "2018 - Presente",
  },
];